### ISSUE TITLE
Isn't `ledger-bitcoin` published on npmjs.com?

### ISSUE THREAD

**Issue by davidknezic** [LedgerHQ/app-bitcoin-new#130]
Hi all, thanks for the wonderful work on bitcoin on Ledger here! 😍 

Due to increasing `CLA_NOT_SUPPORTED` error reports at [pocketbitcoin.com](https://pocketbitcoin.com) I started upgrading our Ledger dependencies. However, even with the latest `@ledgerhq/hw-app-btc` I still seem to be getting these errors with my Ledger Bitcoin app at `2.1.1`. So I found out about this separate repository here.

I noticed there's a completely new client library `ledger-bitcoin` in here. When it was introduced in #22 it was implied it would be published on npmjs.com. However, this doesn't seem to be the case yet?

Is this new library ready to use yet and available somewhere?

**Comment by bigspider** [comment]
Hi!
I think the main missing feature missing from the current `hw-app-btc` (apart from multisig/miniscript/etc.) should be the message signing API, while other things should work; hopefully it will be fixed soon.

The JS library from this repo is good enough to use (but it only works with the 2.1.0 app and above, which I can imagine is a bit annoying for integrations if asking users to upgrade the app is not an option).

While I was recently planning to deprecate it in favor of bindings from the Rust library... creating such bindings proved less straightforward than I hoped. Therefore, I think I'll publish it at some point, but I postponed doing it because I expect some breaking changes soon in its interface (mostly due to the coming release which adds support for taproot scripts).

Until it's published on npm, copying it locally works, and integrations using it won't break later − as future upgrades to the bitcoin app will be backwards-compatible.

Feel free to come find me on [Ledger's Discord](https://developers.ledger.com/discord-pro) (on the #bitcoin channel) if you have any issue.

**Comment by davidknezic** [comment]
>I think the main missing feature missing from the current hw-app-btc (apart from multisig/miniscript/etc.) should be the message signing API, while other things should work; hopefully it will be fixed soon.

You're right, the `CLA_NOT_SUPPORTED` only appears further down our integration, when we try to use `appBtc.signMessage`. Is a fix already in progress or a contribution possible? We're very reliant on message signing.

I'll definitely give `ledger-bitcoin` a go also. We're very excited about the new capabilities you've built with the new bitcoin app and its client libs. 👏 (miniscript!)

I guess our users wouldn't mind upgrading during their Pocket setup. The fact that `hw-app-btc` supports pre `2.1` apps is quite great though, too. Will think about it.

**Comment by bigspider** [comment]
The issue with `signMessage` is already reported to the Ledger Live team, it will most likely be addressed at some point, but I don't know about the timeline. If you want to give it a stab, the package is [here](https://github.com/LedgerHQ/ledger-live/tree/develop/libs/ledgerjs/packages/hw-app-btc), and the `signMessage` function is still only implemented for the old protocol. The only complication in cloning the code from `ledger-bitcoin` should be that the return value `signMessage` return the low level parts `v`, `r`, `s` of the signature, while the new library returns the standard encoding used in bitcoin.

**Comment by davidknezic** [comment]
Thanks a lot @bigspider! It was fairly simple to get it to work in `hw-app-btc`, by adding `signMessage` to the `BtcOld` and `BtcNew` classes.

https://github.com/davidknezic/ledger-live/commit/6de5bb6ec23fe96ab554835aeaf927a7e10e6ca0

I [published my build to npm](https://www.npmjs.com/package/@pocketbitcoin/hw-app-btc) and was able to confirm it works with the Bitcoin app `2.1.0+`.

During testing we found out that now the older Bitcoin app versions (`2.0.0`) fail with `Ledger device: INS_NOT_SUPPORTED (0x6d00)`. We'll try to figure out why this is and plan to open a PR as soon as things are running smoothly. If you have a clue why this error happens, would appreciate the feedback. :)

**Comment by bigspider** [comment]
> Thanks a lot @bigspider! It was fairly simple to get it to work in `hw-app-btc`, by adding `signMessage` to the `BtcOld` and `BtcNew` classes.

That's amazing, looks good!

> During testing we found out that now the older Bitcoin app versions (`2.0.0`) fail with `Ledger device: INS_NOT_SUPPORTED (0x6d00)`. We'll try to figure out why this is and plan to open a PR as soon as things are running smoothly. If you have a clue why this error happens, would appreciate the feedback. :)

That might be because the new `signMessage` was missing in the `2.0.0` release (added in `2.0.2`); although, the intention was to use the legacy protocol for any version below `2.1.0` (since all the versions below that still support the legacy protocol).
I guess something is wrong with the version detection, but that's unrelated to your code and should be fixed elsewhere if that's the case.

**Comment by bigspider** [comment]
Yeah, hw-app-btc is defaulting to the new app's protocol regardless of the app version: https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledgerjs/packages/hw-app-btc/src/Btc.ts#L53-L59, and `changeImplIfNecessary` doesn't correctly switch version there.

I'll raise the issue separately.

**Comment by bigspider** [comment]
@davidknezic: I opened a [PR in ledger-live](https://github.com/LedgerHQ/ledger-live/pull/2952) that should fix the versioning issues; together with your work, it should make `hw-app-btc` work transparently for all the app versions.

I also did some work on `ledger-bitcoin`, and once [this PR](https://github.com/LedgerHQ/app-bitcoin-new/pull/132) is merged, I think it makes sense to push it to npm as well.

**Comment by davidknezic** [comment]
Wonderful, thanks a lot @bigspider!

We've rebased our changes to your fix and deployed to production yesterday and can confirm that it's been working well for both 2.1.0+ users and users of the older app/protocol. As soon as your change is merged, I'll open a follow-up PR.

**Comment by bigspider** [comment]
I just published [ledger-bitcoin](https://www.npmjs.com/package/ledger-bitcoin) on npm :)

Closing this issue, but feel free to comment further.
