### ISSUE TITLE
Ledger device: UNKNOWN_ERROR (0xb008) on many multisig operations (v2.2.0-beta)

### ISSUE THREAD

**Issue by waldenraines** [LedgerHQ/app-bitcoin-new#213]
While using the bitcoin testnet 2.2.0-beta app I am getting the following on any operation that requires registering (such as signing, confirming addresses, or confirming the wallet policy):

```
Ledger device: UNKNOWN_ERROR (0xb008)
```

Can easily reproduce by initializing a device as per the instructions at https://unchained-capital.github.io/caravan/#/test and running through the testnet part of the test suite.

The only thing that is working in our test suite on the testnet 2.2.0-beta firmware exporting testnet public keys and xpubs.

**Comment by bigspider** [comment]
Hi @waldenraines, thanks for the report!
That's strange as there should be any change related to non-miniscript policies.

Any chance the weird version `2.2.0-beta` somehow messes with the Ledger app version detection used in Caravan? That seems compatible with using the old `hw-app-btc` (which does not support multisig with the new app) instead of `ledger-bitcoin`.

I'm able to run the test suite locally on the ae03b7a commit (master appears to be broken, btw - I can't run tests at all).
Is there an easy way to print the USB logs during the tests?

**Comment by waldenraines** [comment]
> I tried with the `2.1.3` and `2.1.2` versions and it fails in the same way. I think it's an unintended change on the caravan test suite side.

Hmm okay, sorry to waste your time on this.

**Comment by bigspider** [comment]
> Hmm okay, sorry to waste your time on this.

No problem at all!
