### ISSUE TITLE
Nano S Plus Liquid Network support and continue updates

### ISSUE THREAD

**Issue by daic11** [LedgerHQ/app-bitcoin-new#233]
Hello why did you stop development of Bitcoin Liquid Network as a Ledger App?
The last update was 3 years ago: https://github.com/LedgerHQ/app-bitcoin/tree/liquid 
It still not support Nano S Plus and I want to build it for myself.
Do you have any recommendation what I should change to build it for Nano S Plus please?

**Comment by bigspider** [comment]
This codebase is an entirely new app, which never had support for Liquid. The old Liquid app was derived from the [legacy bitcoin app](https://github.com/LedgerHQ/app-bitcoin).

Of course, since Liquid is very similar to bitcoin, it shouldn't be too difficult to fork this codebase and adapt it to Liquid; however, it is nonetheless quite a complex app, and that's not planned at this time.

You can refer to the usual developer resources like for any other app, or [get in touch on Discord](https://developers.ledger.com/docs/device-app/introduction/community) if you have development questions.

**Comment by daic11** [comment]
Thank you for the response!
For now I am trying to build the legacy liquid supporting app for Nano S+.
