### ISSUE TITLE
Using sha256 returns an error (0x6a80)

### ISSUE THREAD

**Issue by AndreasGassmann** [LedgerHQ/app-bitcoin-new#257]
I have been experimenting with miniscript and ledger, and I ran into numerous issues. If I register a simple policy like `wsh(sortedmulti(2,@0/**,@1/**))`, everything seems to work. So I assume my project is set up correctly.

For our use-case, we would need a single public key in the script, but it seems, according to https://github.com/LedgerHQ/app-bitcoin-new/issues/210 and other issues I found, that this is not yet possible.

I saw that according to the source code, the `sha256` instruction should be supported: https://github.com/LedgerHQ/app-bitcoin-new/blob/master/src/common/wallet.h#L139. However, I was not able to get this to work. This is the code I tried:

```javascript
const multisigPolicy = new WalletPolicy(
  "Test",
  'wsh(sha256(9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08))', // Hash of "test"
  []
)
const [policyId, policyHmac] = await app.registerWallet(multisigPolicy)
```

I receive the following error:

`TransportStatusError: Ledger device: Invalid data received (0x6a80)`

I have tried many different ways, eg. using a `@0` placeholder and passing the hash in the `keys` array, I also tried other instructions like `ripemd`, but no luck.

Am I doing something wrong here, or is this feature not supported? According to https://github.com/LedgerHQ/app-bitcoin-new/blob/develop/doc/wallet.md it should work because the possible values are `any valid [miniscript](https://bitcoin.sipa.be/miniscript) template (only inside top-level wsh, or in TREE).`. (NOTE: I'm not sure if my miniscript is valid, it cannot be analyzed by https://bitcoin.sipa.be/miniscript. However, I tried other examples with the sha256 hash and they also didn't work, the example I used here is the simplest form to eliminate any other errors.)

**Comment by bigspider** [comment]
The app doesn't just check the _validity_ of the miniscript, but also whether it is _sane_, that is, it satisfies a bunch of stricter security properties. Read for example [here](https://bitcoin.stackexchange.com/questions/113878/what-is-a-sane-miniscript-how-does-it-differ-to-a-valid-miniscript).

A `sha256()` fragment is not sane because satisfying it doesn't require a signature. This is generally unsafe because it makes the transaction malleable: someone could see your transaction in the mempool, and make a different valid transaction that sends somewhere else the money of an input protected with such a script (that is: they can steal the money).

A miniscript like `and_v(v:pk(@0),sha256(9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08))` (compiled from `and(pk(A),sha256(9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08))`  on https://bitcoin.sipa.be/miniscript) should work correctly, as the presence of a signature removed the malleability concerns. In general, you always want at least a signature as part of the spending policy.

**Comment by bigspider** [comment]
If the PSBT is wrong, there is a very high chance that the app would throw an error, as there are many checks that depend con the content of the PSBT.

---

I don't think that's a good use case for using hashes in miniscript. Two immediate problems:
- these scripts waste space, by using unnecessarily large scripts, as they put data on-chain that doesn't have any purpose; that results in higher transaction fees
- these scripts are easy to fingerprint. Worse, an external observer can trivially recognize _all_ the transactions of all your users, since they would be recycling the same 3 pubkeys for each user (only the 'user_hash' changes among different users), which end up on-chain.

I think you should rather look for solutions that generate unique pubkeys for each user based on the `user_hash`. Assuming that the `user_hash` is 32 bytes, a solution might be to generate "synthetic xpubs" for each user as follows:
- decode the xpub/tpub (see [BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki))
- replace the chaincode with the `user_hash`

Repeating this process for each of the three keys, you can then use a simply policy like `wsh(multi(1,@0/<0;1>/*,@1/<0;1>/*,@2/<0;1>/*))` (or the same with `sortedmulti`).
This avoid wasting space, and makes it impossible for an external observer to distinguish these UTXOs from any other 1-of-3 multisig (assuming that the `user_hash` of each user is kept private).

There might of course be other approaches.

**Comment by dcale** [comment]
> If the PSBT is wrong, there is a very high chance that the app would throw an error, as there are many checks that depend con the content of the PSBT.

ok, but do you have an example of a PSBT that is "right"? Like which fields are required, etc?

Your proposed solution is also interesting but would not solve the issue, because even for a normal multisig (or even a 'wsh(pk(XXX))') we cannot create a valid PSBT ledger would sign.
